insert into oauth_client_details
    (
    client_id,
    resource_ids,
    client_secret,
    scope,
    authorized_grant_types,
    web_server_redirect_uri,
    authorities,
    access_token_validity,
    refresh_token_validity,
    additional_information,
    autoapprove
    )
values
    (
        'client_id_1',
        'resource_id_1',
        'client_secret_1',
        'scope_1',
        'authorized_grant_types_1',
        'web_server_redirect_uri_1',
        'authorities_1',
        1,
        1,
        'additional_information_1',
        'autoapprove_1', 
);